import type { DailyPmsLog, PmsLogValue, PredictionResult } from '../types';
import { formatDate, todayLocal } from '../lib/date';
export function Home({logs,prediction,onLog,onOpenCalendar}:{logs:DailyPmsLog[];prediction:PredictionResult;onLog:(d:string,v?:PmsLogValue)=>void;onOpenCalendar:()=>void}){
 const today=todayLocal(); const current=logs.find(l=>l.date===today)?.value;
 return <main className="screen home-screen"><section className="hero-card card"><div><p className="eyebrow">Today</p><h1>{formatDate(today,{weekday:'long',day:'numeric',month:'long'})}</h1><p className="muted">One tap is enough. Logging is always optional.</p></div><div className="today-controls"><button className={current==='pms'?'active pms':''} onClick={()=>onLog(today,'pms')}><span className="control-orb pms"/>PMS-like symptoms</button><button className={current==='no_pms'?'active no':''} onClick={()=>onLog(today,'no_pms')}><span className="control-orb no"/>No symptoms</button>{current&&<button className="clear-today" onClick={()=>onLog(today,undefined)}>Clear today's entry</button>}</div></section>
 <section className="prediction-card card"><div className="prediction-header"><div><p className="eyebrow">Possible upcoming window</p>{prediction.status==='prediction'?<h2>{formatDate(prediction.predictedStart!,{day:'numeric',month:'long'})} – {formatDate(prediction.predictedEnd!,{day:'numeric',month:'long',year:'numeric'})}</h2>:<h2>{prediction.status==='insufficient_data'?'More history needed':'No stable pattern yet'}</h2>}</div><div className={`reliability ${prediction.confidence}`}><small>Reliability</small><strong>{prediction.reliability}%</strong><span>{prediction.confidence}</span></div></div><div className="reliability-track"><i style={{width:`${prediction.reliability}%`}}/></div><p>{prediction.explanation}</p><dl className="prediction-stats"><div><dt>PMS clusters</dt><dd>{prediction.clusterCount}</dd></div><div><dt>History used</dt><dd>{prediction.historyDays} days</dd></div><div><dt>PMS days</dt><dd>{prediction.totalPmsDays}</dd></div></dl></section>
 <section className="start-card card"><div><p className="eyebrow">Add your history</p><h2>Retroactive entries improve the forecast</h2><p className="muted">Tap past dates or add a complete historical symptom range from the calendar.</p></div><button className="secondary-button" onClick={onOpenCalendar}>Open calendar</button></section>
 <section className="safety-card card"><strong>Pattern estimate, not medical advice</strong><p>Symptoms while using hormonal contraception may have many causes. Lynera only detects timing patterns in your entries.</p></section></main>
}
